# Generated by Django 5.0.2 on 2025-10-19 19:33

import core.validators.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "refactor_database"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartmentpricing",
            name="apartment",
        ),
        migrations.DeleteModel(
            name="AuditLog",
        ),
        migrations.RemoveField(
            model_name="document",
            name="apartment",
        ),
        migrations.RemoveField(
            model_name="document",
            name="lease",
        ),
        migrations.RemoveField(
            model_name="document",
            name="parent_document",
        ),
        migrations.RemoveField(
            model_name="document",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="document",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="apartment",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="building",
        ),
        migrations.AlterUniqueTogether(
            name="leasetenant",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="leasetenant",
            name="lease",
        ),
        migrations.RemoveField(
            model_name="leasetenant",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="lease",
        ),
        migrations.RemoveField(
            model_name="lease",
            name="actual_end_date",
        ),
        migrations.RemoveField(
            model_name="lease",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="lease",
            name="lease_number",
        ),
        migrations.RemoveField(
            model_name="lease",
            name="status",
        ),
        migrations.AlterField(
            model_name="lease",
            name="due_day",
            field=models.PositiveIntegerField(
                help_text="Dia do vencimento do aluguel",
                validators=[core.validators.model_validators.validate_due_day],
            ),
        ),
        migrations.AlterField(
            model_name="lease",
            name="start_date",
            field=models.DateField(db_index=True, help_text="Data de início da locação"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="cpf_cnpj",
            field=models.CharField(
                db_index=True,
                help_text="CPF (ou CNPJ em caso de empresa)",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("Solteiro(a)", "Solteiro(a)"),
                    ("Casado(a)", "Casado(a)"),
                    ("Divorciado(a)", "Divorciado(a)"),
                    ("Viúvo(a)", "Viúvo(a)"),
                    ("União Estável", "União Estável"),
                ],
                help_text="Estado civil",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(fields=["start_date"], name="lease_start_date_idx"),
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(fields=["contract_generated"], name="lease_contract_gen_idx"),
        ),
        migrations.DeleteModel(
            name="ApartmentPricing",
        ),
        migrations.DeleteModel(
            name="Document",
        ),
        migrations.DeleteModel(
            name="Expense",
        ),
        migrations.DeleteModel(
            name="LeaseTenant",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
