# Generated by Django 5.2 on 2025-04-14 21:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.PositiveIntegerField(help_text='Número da rua (ex.: 836 ou 850)', unique=True)),
                ('name', models.CharField(help_text='Nome do prédio', max_length=100)),
                ('address', models.CharField(help_text='Endereço completo do prédio', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do móvel (ex.: Fogão, Geladeira, etc.)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Número único do apartamento no prédio')),
                ('interfone_configured', models.BooleanField(default=False, help_text='Indica se o interfone está configurado')),
                ('contract_generated', models.BooleanField(default=False, help_text='Contrato foi gerado?')),
                ('contract_signed', models.BooleanField(default=False, help_text='Contrato foi assinado?')),
                ('rental_value', models.DecimalField(decimal_places=2, help_text='Valor do aluguel', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cleaning_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Taxa de limpeza', max_digits=10)),
                ('max_tenants', models.PositiveIntegerField(help_text='Número máximo de inquilinos permitidos')),
                ('is_rented', models.BooleanField(default=False, help_text='Apartamento alugado ou não')),
                ('lease_date', models.DateField(blank=True, help_text='Data da locação (caso alugado)', null=True)),
                ('last_rent_increase_date', models.DateField(blank=True, help_text='Data do último reajuste do aluguel', null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='core.building')),
                ('furnitures', models.ManyToManyField(blank=True, help_text='Móveis presentes no apartamento', related_name='apartments', to='core.furniture')),
            ],
            options={
                'ordering': ['building__street_number', 'number'],
                'unique_together': {('building', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome completo ou razão social', max_length=150)),
                ('cpf_cnpj', models.CharField(help_text='CPF (ou CNPJ em caso de empresa)', max_length=20, unique=True)),
                ('is_company', models.BooleanField(default=False, help_text='Indica se é Pessoa Jurídica')),
                ('rg', models.CharField(blank=True, help_text='RG (não obrigatório para empresas)', max_length=20, null=True)),
                ('phone', models.CharField(help_text='Telefone de contato', max_length=20)),
                ('marital_status', models.CharField(help_text='Estado civil', max_length=50)),
                ('profession', models.CharField(help_text='Profissão', max_length=100)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Valor da caução, se houver', max_digits=10, null=True)),
                ('cleaning_fee_paid', models.BooleanField(default=False, help_text='Indica se pagou a taxa de limpeza')),
                ('tag_deposit_paid', models.BooleanField(default=False, help_text='Indica se o caução das tags já foi pago')),
                ('rent_due_day', models.PositiveIntegerField(default=1, help_text='Dia do vencimento do aluguel')),
                ('furnitures', models.ManyToManyField(blank=True, help_text='Móveis próprios do inquilino', related_name='tenants', to='core.furniture')),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Data de início da locação')),
                ('validity_months', models.PositiveIntegerField(help_text='Validade do contrato em meses')),
                ('due_day', models.PositiveIntegerField(help_text='Dia do vencimento do aluguel')),
                ('rental_value', models.DecimalField(decimal_places=2, help_text='Valor do aluguel', max_digits=10)),
                ('cleaning_fee', models.DecimalField(decimal_places=2, help_text='Valor da taxa de limpeza', max_digits=10)),
                ('tag_fee', models.DecimalField(decimal_places=2, default=0, help_text='Valor da caução da tag', max_digits=10)),
                ('contract_generated', models.BooleanField(default=False, help_text='Indica se o contrato foi gerado')),
                ('contract_signed', models.BooleanField(default=False, help_text='Indica se o contrato foi assinado')),
                ('interfone_configured', models.BooleanField(default=False, help_text='Indica se o interfone foi configurado')),
                ('warning_count', models.PositiveIntegerField(default=0, help_text='Número de avisos do inquilino por descumprimento das regras')),
                ('apartment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lease', to='core.apartment')),
                ('responsible_tenant', models.ForeignKey(help_text='Inquilino responsável pela locação', on_delete=django.db.models.deletion.PROTECT, related_name='leases_responsible', to='core.tenant')),
                ('tenants', models.ManyToManyField(help_text='Inquilinos que residem no apartamento', related_name='leases', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do dependente', max_length=150)),
                ('phone', models.CharField(help_text='Telefone do dependente', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='core.tenant')),
            ],
        ),
    ]
