# Generated by Django 5.2 on 2025-04-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="number_of_tenants",
            field=models.PositiveIntegerField(default=1, help_text="Número de inquilinos no contrato"),
        ),
    ]
