# Generated by Django 5.0.2 on 2025-10-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_add_validators_and_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="apartment",
            index=models.Index(fields=["building", "is_rented"], name="apt_building_rented_idx"),
        ),
        migrations.AddIndex(
            model_name="apartment",
            index=models.Index(fields=["is_rented", "rental_value"], name="apt_rented_value_idx"),
        ),
        migrations.AddIndex(
            model_name="apartment",
            index=models.Index(fields=["building", "number"], name="apt_building_number_idx"),
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(fields=["apartment", "start_date"], name="lease_apt_date_idx"),
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(fields=["responsible_tenant", "start_date"], name="lease_tenant_date_idx"),
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(fields=["contract_generated", "start_date"], name="lease_status_date_idx"),
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(fields=["due_day", "start_date"], name="lease_due_date_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["is_company", "name"], name="tenant_type_name_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["marital_status", "is_company"], name="tenant_status_type_idx"),
        ),
    ]
