# Generated by Django 5.0.2 on 2025-12-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_add_composite_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lease",
            name="number_of_tenants",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Número de ocupantes (para cálculo de taxa de tag). Pode ser maior que o número de inquilinos registrados.",
            ),
        ),
    ]
