# Generated by Django 5.0.2 on 2025-12-21 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_add_tenant_user_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Conta de usuário associada para acesso ao portal do inquilino",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tenant_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
