# Generated by Django 5.0.2 on 2025-12-21 16:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_tenant_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="Data/hora de criação do registro",
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuário que criou o registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, editable=False, help_text="Data/hora da exclusão", null=True),
        ),
        migrations.AddField(
            model_name="apartment",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuário que excluiu o registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                editable=False,
                help_text="Indica se o registro foi excluído",
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="Data/hora da última modificação",
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuário que modificou o registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="Data/hora de criação do registro",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuário que criou o registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="deleted_at",
            field=models.DateTimeField(blank=True, editable=False, help_text="Data/hora da exclusão", null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuário que excluiu o registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                editable=False,
                help_text="Indica se o registro foi excluído",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="Data/hora da última modificação",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuário que modificou o registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dependent",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="Data/hora de criação do registro",
            ),
        ),
        migrations.AddField(
            model_name="dependent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuário que criou o registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dependent",
            name="deleted_at",
            field=models.DateTimeField(blank=True, editable=False, help_text="Data/hora da exclusão", null=True),
        ),
        migrations.AddField(
            model_name="dependent",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuário que excluiu o registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dependent",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                editable=False,
                help_text="Indica se o registro foi excluído",
            ),
        ),
        migrations.AddField(
            model_name="dependent",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="Data/hora da última modificação",
            ),
        ),
        migrations.AddField(
            model_name="dependent",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuário que modificou o registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="furniture",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="Data/hora de criação do registro",
            ),
        ),
        migrations.AddField(
            model_name="furniture",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuário que criou o registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="furniture",
            name="deleted_at",
            field=models.DateTimeField(blank=True, editable=False, help_text="Data/hora da exclusão", null=True),
        ),
        migrations.AddField(
            model_name="furniture",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuário que excluiu o registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="furniture",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                editable=False,
                help_text="Indica se o registro foi excluído",
            ),
        ),
        migrations.AddField(
            model_name="furniture",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="Data/hora da última modificação",
            ),
        ),
        migrations.AddField(
            model_name="furniture",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuário que modificou o registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="Data/hora de criação do registro",
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuário que criou o registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="deleted_at",
            field=models.DateTimeField(blank=True, editable=False, help_text="Data/hora da exclusão", null=True),
        ),
        migrations.AddField(
            model_name="lease",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuário que excluiu o registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                editable=False,
                help_text="Indica se o registro foi excluído",
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="Data/hora da última modificação",
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuário que modificou o registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="Data/hora de criação do registro",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuário que criou o registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="deleted_at",
            field=models.DateTimeField(blank=True, editable=False, help_text="Data/hora da exclusão", null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuário que excluiu o registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                editable=False,
                help_text="Indica se o registro foi excluído",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="Data/hora da última modificação",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuário que modificou o registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
