# Generated by Django 5.2.10 on 2026-01-19 17:13

import core.validators.brazilian
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_add_audit_softdelete_mixins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dependent",
            name="phone",
            field=models.CharField(
                help_text="Telefone do dependente",
                max_length=20,
                validators=[core.validators.brazilian.validate_brazilian_phone],
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="phone",
            field=models.CharField(
                help_text="Telefone de contato",
                max_length=20,
                validators=[core.validators.brazilian.validate_brazilian_phone],
            ),
        ),
    ]
