# Generated by Django 5.2.10 on 2026-01-19 19:47

import core.validators.brazilian
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_dependent_phone_alter_tenant_phone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Landlord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Data/hora de criação do registro",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Data/hora da última modificação",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        help_text="Indica se o registro foi excluído",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, editable=False, help_text="Data/hora da exclusão", null=True
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Nome completo ou razão social", max_length=200),
                ),
                (
                    "nationality",
                    models.CharField(
                        default="Brasileira", help_text="Nacionalidade", max_length=100
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("Solteiro(a)", "Solteiro(a)"),
                            ("Casado(a)", "Casado(a)"),
                            ("Divorciado(a)", "Divorciado(a)"),
                            ("Viúvo(a)", "Viúvo(a)"),
                            ("União Estável", "União Estável"),
                        ],
                        help_text="Estado civil",
                        max_length=50,
                    ),
                ),
                ("cpf_cnpj", models.CharField(help_text="CPF ou CNPJ", max_length=20)),
                (
                    "rg",
                    models.CharField(
                        blank=True, help_text="RG (opcional)", max_length=20, null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Telefone de contato",
                        max_length=20,
                        validators=[core.validators.brazilian.validate_brazilian_phone],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Email de contato", max_length=254, null=True
                    ),
                ),
                ("street", models.CharField(help_text="Rua/Avenida", max_length=200)),
                ("street_number", models.CharField(help_text="Número", max_length=20)),
                (
                    "complement",
                    models.CharField(
                        blank=True, help_text="Complemento", max_length=100, null=True
                    ),
                ),
                ("neighborhood", models.CharField(help_text="Bairro", max_length=100)),
                ("city", models.CharField(help_text="Cidade", max_length=100)),
                ("state", models.CharField(help_text="Estado", max_length=50)),
                ("zip_code", models.CharField(help_text="CEP", max_length=10)),
                ("country", models.CharField(default="Brasil", help_text="País", max_length=100)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Locador ativo (apenas um pode estar ativo)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Usuário que criou o registro",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Usuário que excluiu o registro",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Usuário que modificou o registro",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Locador",
                "verbose_name_plural": "Locadores",
            },
        ),
    ]
