# Generated by Django 5.0.2

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed_initial_rules(apps, schema_editor):
    """Seed initial contract rules from contract_rules.py."""
    ContractRule = apps.get_model("core", "ContractRule")

    # Rules from core/contract_rules.py (converted to <strong> tags)
    initial_rules = [
        (
            "É <strong>proíbido fumar</strong> nas <strong>áreas comuns</strong> do condomínio, <strong>inclusive</strong>"
            " na <strong>área comum entre os 2 portões de frente na</strong><strong> Avenida Circular 836</strong>"
            ", e na <strong>garagem da Avenida Circular 850</strong>. Dentro dos kitnets é permitido fumar, porém é obrigatório fechar as janelas."
        ),
        (
            "É <strong>proibído perturbar o sossego e o bem-estar público</strong> da população pela emissão de sons e ruídos"
            "  por quaisquer fontes ou atividades que ultrapassem os níveis máximos de intensidade fixados por lei."
            " O <strong>horário de silêncio</strong> é <strong>entre 23:00 e 8:00 de Domingo a</strong>"
            "<strong> Segunda-feira</strong> e <strong>entre 00:00 e 9:00 na Sexta-feira e Sábado</strong>."
            "<strong> Vale ressaltar que fora desse horário nãó é permitido sons que perturbem os vizinhos durante o dia</strong>."
        ),
        (
            "Áreas comuns, como a área de frente do prédio e corredores, são de propriedade do condomínio, motivo pelo qual nenhum morador pode utilizá-la"
            " para seu interesse particular, como armazenamento de itens pessoais ou outros usos particulares."
            " A <strong>única exceção</strong> é que o LOCADOR permite que <strong>motocicletas</strong>"
            " sejam deixados na área comum em frente ao condomínio, <strong>entre os 2 portões de frente na Av. Circular 836</strong>."
        ),
        "<strong>É proíbido deixar qualquer portão do condomínio aberto.</strong>",
        (
            "<strong>É proíbido abrir o portão para não moradores do condomínio, sem consentimento da pessoa que está sendo buscada."
            " Para receber</strong><strong> visitas ou entregas, SEMPRE INFORME O NÚMERO DO SEU APARTAMENTO,"
            " para receber a ligação do interfone e poder ir até o portão</strong><strong> para receber a visita / entrega</strong>."
        ),
        (
            "É <strong>proíbido</strong> a moradia de <strong>animais de estimação</strong> nos kitnets"
            ", e também a circulação dos mesmos nas áreas comuns do condomínio."
        ),
        (
            "Para <strong>moradores da Av. Circular 850, é proíbido o uso da garagem</strong>"
            ", para deixar <strong>qualquer tipo de veículo</strong>."
        ),
    ]

    for index, content in enumerate(initial_rules):
        ContractRule.objects.create(
            content=content,
            order=index,
            is_active=True,
        )


def reverse_seed(apps, schema_editor):
    """Remove seeded rules."""
    ContractRule = apps.get_model("core", "ContractRule")
    ContractRule.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0010_add_landlord_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Data/hora de criação do registro",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Data/hora da última modificação",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        help_text="Indica se o registro foi excluído",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Data/hora da exclusão",
                        null=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Conteúdo HTML da regra (use <strong> para negrito)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Ordem de exibição (menores valores aparecem primeiro)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Se a regra deve ser incluída nos contratos",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Usuário que criou o registro",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Usuário que modificou o registro",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Usuário que excluiu o registro",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Regra do Condomínio",
                "verbose_name_plural": "Regras do Condomínio",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="contractrule",
            index=models.Index(
                fields=["is_active", "order"], name="rule_active_order_idx"
            ),
        ),
        # Seed initial data
        migrations.RunPython(seed_initial_rules, reverse_seed),
    ]
