# Generated by Django 5.2.10 on 2026-03-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_add_expense_category_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="is_offset",
            field=models.BooleanField(
                default=False,
                help_text="Desconto: valor é subtraído do total da pessoa (compra feita no cartão dela, mas para os sogros/Camila).",
            ),
        ),
    ]
