# Generated by Django 5.2.10 on 2026-03-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_add_person_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Data fim para gastos fixos recorrentes. Projeção para após esta data.",
                null=True,
            ),
        ),
    ]
