# Generated by Django 5.2.12 on 2026-03-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_add_expense_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="cleaning_fee_paid",
            field=models.BooleanField(default=False, help_text="Taxa de limpeza paga"),
        ),
        migrations.AddField(
            model_name="lease",
            name="deposit_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor da caução",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="tag_deposit_paid",
            field=models.BooleanField(default=False, help_text="Caução de tags paga"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="warning_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Quantidade de avisos do inquilino"
            ),
        ),
    ]
