# Generated by Django 5.2.12 on 2026-03-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_migrate_data_and_rename"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="lease",
            name="lease_due_date_idx",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="contract_generated",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="contract_signed",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="interfone_configured",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="lease_date",
        ),
        migrations.RemoveField(
            model_name="lease",
            name="cleaning_fee",
        ),
        migrations.RemoveField(
            model_name="lease",
            name="due_day",
        ),
        migrations.RemoveField(
            model_name="lease",
            name="rental_value",
        ),
        migrations.RemoveField(
            model_name="lease",
            name="warning_count",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="cleaning_fee_paid",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="deposit_amount",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="tag_deposit_paid",
        ),
        migrations.AlterField(
            model_name="apartment",
            name="is_rented",
            field=models.BooleanField(
                default=False,
                help_text="Atualizado automaticamente via signal de Lease",
            ),
        ),
    ]
