# Generated by Django 5.2.12 on 2026-03-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_lease_apartment_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="initial_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Saldo devedor anterior ao sistema",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="initial_balance_date",
            field=models.DateField(
                blank=True,
                help_text="Mês de referência do saldo devedor (dia 1 do mês)",
                null=True,
            ),
        ),
    ]
