# Generated by Django 5.2.12 on 2026-03-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_rentadjustment"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="last_rent_increase_date",
            field=models.DateField(
                blank=True,
                help_text="Data do último reajuste. Referência para o próximo reajuste anual.",
                null=True,
            ),
        ),
    ]
