# Generated by Django 5.2.12 on 2026-03-27 15:06

from django.db import migrations


def populate_lease_last_rent_increase_date(apps, schema_editor):
    """Copy apartment.last_rent_increase_date to lease.last_rent_increase_date.

    For leases that have RentAdjustment records, use the most recent adjustment date.
    Otherwise, fall back to apartment.last_rent_increase_date, then lease.start_date.
    """
    Lease = apps.get_model("core", "Lease")
    RentAdjustment = apps.get_model("core", "RentAdjustment")

    for lease in Lease._default_manager.select_related("apartment").filter(is_deleted=False):
        last_adj = (
            RentAdjustment._default_manager.filter(lease=lease, is_deleted=False)
            .order_by("-adjustment_date")
            .first()
        )
        if last_adj:
            lease.last_rent_increase_date = last_adj.adjustment_date
        elif lease.apartment.last_rent_increase_date:
            lease.last_rent_increase_date = lease.apartment.last_rent_increase_date
        else:
            lease.last_rent_increase_date = lease.start_date
        lease.save(update_fields=["last_rent_increase_date"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_lease_last_rent_increase_date"),
    ]

    operations = [
        migrations.RunPython(
            populate_lease_last_rent_increase_date,
            migrations.RunPython.noop,
        ),
    ]
