# Generated by Django 5.2.12 on 2026-03-27 15:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_financial_settings_rent_adjustment_percentage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financialsettings",
            name="rent_adjustment_percentage",
        ),
        migrations.AddField(
            model_name="landlord",
            name="rent_adjustment_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Percentual padrão de reajuste anual do aluguel (ex: 5.23)",
                max_digits=5,
            ),
        ),
    ]
