# Generated by Django 5.2.12 on 2026-03-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_remove_financialsettings_rent_adjustment_percentage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPCAIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_month",
                    models.DateField(
                        help_text="Primeiro dia do mês de referência (ex: 2026-03-01)",
                        unique=True,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=13,
                        help_text="Número-índice IPCA (base dez/1993 = 100)",
                        max_digits=20,
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-reference_month"],
                "indexes": [
                    models.Index(
                        fields=["reference_month"], name="ipca_index_month_idx"
                    )
                ],
            },
        ),
    ]
