# Generated by Django 5.2.12 on 2026-03-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_ipca_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="pending_rental_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Novo valor de aluguel pendente (reajuste com data futura).",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="pending_rental_value_date",
            field=models.DateField(
                blank=True,
                help_text="Data a partir da qual o pending_rental_value entra em vigor.",
                null=True,
            ),
        ),
    ]
