# Generated by Django 5.2.12 on 2026-03-28 21:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_person_payment_schedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Data/hora de criação do registro",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Data/hora da última modificação",
                    ),
                ),
                (
                    "reference_month",
                    models.DateField(
                        help_text="Primeiro dia do mês de referência (ex: 2026-03-01)"
                    ),
                ),
                (
                    "total_rent_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_extra_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_person_payments_received",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_card_installments",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_loan_installments",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_utility_bills",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_fixed_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_one_time_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_employee_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_owner_repayments",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_person_stipends",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_debt_installments",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_property_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cumulative_ending_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Saldo acumulado ao final do mês (snapshot anterior + net_balance deste mês). Serve como ponto de partida para o controle diário do mês seguinte.",
                        max_digits=12,
                    ),
                ),
                (
                    "detailed_breakdown",
                    models.JSONField(
                        default=dict,
                        help_text="Breakdown completo por categoria com itens individuais",
                    ),
                ),
                (
                    "is_finalized",
                    models.BooleanField(
                        default=False,
                        help_text="True quando o mês está oficialmente fechado",
                    ),
                ),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Usuário que criou o registro",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Usuário que modificou o registro",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-reference_month"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("reference_month",), name="unique_month_snapshot"
                    )
                ],
            },
        ),
    ]
