# Generated by Django 5.2.12 on 2026-03-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_mobile_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialsettings",
            name="default_pix_key",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="default_pix_key_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cpf", "CPF"),
                    ("cnpj", "CNPJ"),
                    ("email", "E-mail"),
                    ("phone", "Telefone"),
                    ("random", "Chave aleatória"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="pix_key",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="person",
            name="pix_key_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cpf", "CPF"),
                    ("cnpj", "CNPJ"),
                    ("email", "E-mail"),
                    ("phone", "Telefone"),
                    ("random", "Chave aleatória"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
