# Generated by Django 5.2.12 on 2026-03-30 02:33

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_mobile_models"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="paymentproof",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
