# Generated by Django 5.2.12 on 2026-04-05 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_alter_paymentproof_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcard",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_cards",
                to="core.person",
            ),
        ),
        migrations.AlterField(
            model_name="employeepayment",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employee_payments",
                to="core.person",
            ),
        ),
        migrations.AlterField(
            model_name="personincome",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incomes",
                to="core.person",
            ),
        ),
        migrations.AlterField(
            model_name="personpayment",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments_received",
                to="core.person",
            ),
        ),
    ]
