# Generated by Django 5.2.12 on 2026-04-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_data_integrity_protect_cascade_constraints"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="apartment",
            index=models.Index(fields=["is_rented"], name="apt_is_rented_idx"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["person", "expense_type"], name="exp_person_type_idx"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["person", "expense_date"], name="exp_person_date_idx"),
        ),
        migrations.AddIndex(
            model_name="expenseinstallment",
            index=models.Index(
                fields=["expense", "due_date", "is_paid"],
                name="inst_exp_date_paid_idx",
            ),
        ),
    ]
