# Generated by Django 5.2.12 on 2026-04-05 20:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_add_missing_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="creditcard",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="employeepayment",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="expenseinstallment",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="rentpayment",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="creditcard",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("person", "nickname"),
                name="unique_active_credit_card",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeepayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("person", "reference_month"),
                name="unique_active_employee_payment",
            ),
        ),
        migrations.AddConstraint(
            model_name="expenseinstallment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("expense", "installment_number"),
                name="unique_active_expense_installment",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentpayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("lease", "reference_month"),
                name="unique_active_rent_payment",
            ),
        ),
    ]
