# Generated by Django 5.2.12 on 2026-04-05 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_soft_delete_unique_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="apartment",
            constraint=models.CheckConstraint(
                condition=models.Q(("rental_value__gte", 0)),
                name="apt_rental_value_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="apartment",
            constraint=models.CheckConstraint(
                condition=models.Q(("cleaning_fee__gte", 0)),
                name="apt_cleaning_fee_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeepayment",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_salary__gte", 0)),
                name="employee_base_salary_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", 0)),
                name="expense_total_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="expenseinstallment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="installment_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="lease",
            constraint=models.CheckConstraint(
                condition=models.Q(("rental_value__gte", 0)),
                name="lease_rental_value_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="personpayment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="person_payment_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentpayment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_paid__gt", 0)),
                name="rent_payment_amount_positive",
            ),
        ),
    ]
