# Generated by Django 5.2.12 on 2026-04-05 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_add_check_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personpaymentschedule",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_schedules",
                to="core.person",
            ),
        ),
    ]
