# Generated by Django 5.2.12 on 2026-04-06 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_person_payment_schedule_protect"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="expense",
            name="expense_total_amount_non_negative",
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gt", 0)),
                name="expense_total_amount_positive",
            ),
        ),
    ]
