# Generated by Django 5.2.12 on 2026-04-06 21:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_add_oauth_exchange_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["is_recurring", "expense_date"],
                name="idx_expense_recurring_date",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["category", "expense_date"], name="idx_expense_category_date"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["person", "is_paid", "expense_date"],
                name="idx_expense_person_paid_date",
            ),
        ),
    ]
