# Generated by Django 5.2.13 on 2026-06-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_add_expense_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lease",
            name="tag_deposit_paid",
            field=models.BooleanField(default=False, help_text="Taxa de tag(s) paga"),
        ),
        migrations.AlterField(
            model_name="lease",
            name="tag_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Valor cobrado pela(s) tag(s) de acesso (não reembolsável)",
                max_digits=10,
            ),
        ),
    ]
