# Generated by Django 5.2.13 on 2026-06-04 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_webpushsubscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="expense",
            name="expense_total_amount_positive",
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", 0)),
                name="expense_total_amount_positive",
            ),
        ),
    ]
