# Generated by Django 5.2.13 on 2026-06-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_remove_expense_expense_total_amount_positive_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialsettings",
            name="rent_tracking_start_date",
            field=models.DateField(
                blank=True,
                help_text="Sistema rastreia aluguéis (cobrança/atraso) a partir desta data; meses anteriores são considerados quitados.",
                null=True,
            ),
        ),
    ]
