# Generated by Django 5.2.13 on 2026-06-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_condominium_building_condominium"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("due_reminder", "Lembrete de vencimento"),
                    ("due_today", "Vencimento hoje"),
                    ("overdue", "Aluguel atrasado"),
                    ("proof_approved", "Comprovante aprovado"),
                    ("proof_rejected", "Comprovante rejeitado"),
                    ("rent_adjustment", "Reajuste de aluguel"),
                    ("admin_notice", "Aviso do admin"),
                    ("new_proof", "Novo comprovante"),
                    ("contract_expiring", "Contrato vencendo"),
                    ("adjustment_eligible", "Reajuste elegível"),
                    ("iptu_overdue_risk", "IPTU: parcela em risco"),
                    ("iptu_parcelamento_lost", "IPTU: parcelamento perdido"),
                ],
                max_length=30,
            ),
        ),
    ]
