# Generated by Django 5.2.13 on 2026-06-11 20:38

from django.db import migrations, models

# Feminine forms were never valid choices (rows holding them broke every partial
# update with a 500 — HF-1); masculine forms were legacy choices, dead after this
# migration. Placeholder values ("-") are NOT mapped: they are fixed manually.
MARITAL_STATUS_NORMALIZATION = {
    "Solteira": "Solteiro(a)",
    "Casada": "Casado(a)",
    "Divorciada": "Divorciado(a)",
    "Viúva": "Viúvo(a)",
    "Solteiro": "Solteiro(a)",
    "Casado": "Casado(a)",
    "Divorciado": "Divorciado(a)",
    "Viúvo": "Viúvo(a)",
}


def normalize_marital_status(apps, schema_editor):
    # _base_manager: historical models don't serialize the custom managers, and the
    # plain manager also reaches soft-deleted rows
    for model_name in ("Tenant", "Landlord"):
        model = apps.get_model("core", model_name)
        for legacy, canonical in MARITAL_STATUS_NORMALIZATION.items():
            model._base_manager.filter(marital_status=legacy).update(marital_status=canonical)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_seed_default_contract_template"),
    ]

    operations = [
        migrations.RunPython(normalize_marital_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="landlord",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("Solteiro(a)", "Solteiro(a)"),
                    ("Casado(a)", "Casado(a)"),
                    ("Divorciado(a)", "Divorciado(a)"),
                    ("Viúvo(a)", "Viúvo(a)"),
                    ("União Estável", "União Estável"),
                ],
                help_text="Estado civil",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("Solteiro(a)", "Solteiro(a)"),
                    ("Casado(a)", "Casado(a)"),
                    ("Divorciado(a)", "Divorciado(a)"),
                    ("Viúvo(a)", "Viúvo(a)"),
                    ("União Estável", "União Estável"),
                ],
                help_text="Estado civil",
                max_length=50,
            ),
        ),
    ]
