# Generated by Django 5.2.13 on 2026-06-12 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_alter_landlord_marital_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apartment",
            options={
                "default_manager_name": "objects",
                "ordering": ["building__street_number", "number"],
            },
        ),
        migrations.AlterModelOptions(
            name="building",
            options={"default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="condominium",
            options={"default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="contractrule",
            options={
                "default_manager_name": "objects",
                "ordering": ["order", "id"],
                "verbose_name": "Regra do Condomínio",
                "verbose_name_plural": "Regras do Condomínio",
            },
        ),
        migrations.AlterModelOptions(
            name="creditcard",
            options={
                "default_manager_name": "objects",
                "ordering": ["person", "nickname"],
            },
        ),
        migrations.AlterModelOptions(
            name="dependent",
            options={"default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="employeepayment",
            options={
                "default_manager_name": "objects",
                "ordering": ["-reference_month"],
            },
        ),
        migrations.AlterModelOptions(
            name="expense",
            options={"default_manager_name": "objects", "ordering": ["-expense_date"]},
        ),
        migrations.AlterModelOptions(
            name="expensecategory",
            options={
                "default_manager_name": "objects",
                "ordering": ["name"],
                "verbose_name_plural": "Expense categories",
            },
        ),
        migrations.AlterModelOptions(
            name="expenseinstallment",
            options={
                "default_manager_name": "objects",
                "ordering": ["due_date", "installment_number"],
            },
        ),
        migrations.AlterModelOptions(
            name="furniture",
            options={"default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="income",
            options={"default_manager_name": "objects", "ordering": ["-income_date"]},
        ),
        migrations.AlterModelOptions(
            name="landlord",
            options={
                "default_manager_name": "objects",
                "verbose_name": "Locador",
                "verbose_name_plural": "Locadores",
            },
        ),
        migrations.AlterModelOptions(
            name="lease",
            options={"default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="paymentproof",
            options={"default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"default_manager_name": "objects", "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="personincome",
            options={"default_manager_name": "objects", "ordering": ["-start_date"]},
        ),
        migrations.AlterModelOptions(
            name="personpayment",
            options={"default_manager_name": "objects", "ordering": ["-payment_date"]},
        ),
        migrations.AlterModelOptions(
            name="personpaymentschedule",
            options={
                "default_manager_name": "objects",
                "ordering": ["reference_month", "due_day"],
            },
        ),
        migrations.AlterModelOptions(
            name="rentadjustment",
            options={
                "default_manager_name": "objects",
                "ordering": ["-adjustment_date"],
            },
        ),
        migrations.AlterModelOptions(
            name="rentpayment",
            options={
                "default_manager_name": "objects",
                "ordering": ["-reference_month"],
            },
        ),
        migrations.AlterModelOptions(
            name="tenant",
            options={"default_manager_name": "objects"},
        ),
        migrations.AlterModelManagers(
            name="apartment",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="building",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="condominium",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="contractrule",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="creditcard",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="dependent",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="employeepayment",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="expense",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="expensecategory",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="expenseinstallment",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="furniture",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="income",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="landlord",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="lease",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="paymentproof",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="person",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="personincome",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="personpayment",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="personpaymentschedule",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="rentadjustment",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="rentpayment",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="tenant",
            managers=[],
        ),
    ]
