# Generated by Django 5.2.13 on 2026-06-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_alter_apartment_options_alter_building_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialsettings",
            name="default_city",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Cidade exibida no PIX (campo 60 do EMV); vazio usa a cidade do locador.",
                max_length=100,
            ),
        ),
    ]
