# Generated by Django 5.2.13 on 2026-06-12 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_normalize_cpf_cnpj"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="expense",
            name="expense_total_amount_positive",
        ),
        migrations.AlterUniqueTogether(
            name="apartment",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="building",
            name="street_number",
            field=models.PositiveIntegerField(
                db_index=True, help_text="Número da rua (ex.: 836 ou 850)"
            ),
        ),
        migrations.AlterField(
            model_name="furniture",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Nome do móvel (ex.: Fogão, Geladeira, etc.)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="rentpayment",
            name="lease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rent_payments",
                to="core.lease",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="cpf_cnpj",
            field=models.CharField(
                db_index=True,
                help_text="CPF (ou CNPJ em caso de empresa)",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="apartment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("building", "number"),
                name="unique_active_apartment_per_building",
            ),
        ),
        migrations.AddConstraint(
            model_name="building",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("street_number",),
                name="unique_active_building_street_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="condominium",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("name",),
                name="unique_active_condominium_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", 0)),
                name="expense_total_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="furniture",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("name",),
                name="unique_active_furniture_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="landlord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_deleted", False)),
                fields=("is_active",),
                name="unique_active_landlord",
            ),
        ),
        migrations.AddConstraint(
            model_name="lease",
            constraint=models.CheckConstraint(
                condition=models.Q(("tag_fee__gte", 0)),
                name="lease_tag_fee_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="lease",
            constraint=models.CheckConstraint(
                condition=models.Q(("deposit_amount__gte", 0)),
                name="lease_deposit_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="lease",
            constraint=models.CheckConstraint(
                condition=models.Q(("pending_rental_value__gte", 0)),
                name="lease_pending_rental_value_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentadjustment",
            constraint=models.CheckConstraint(
                condition=models.Q(("previous_value__gte", 0)),
                name="rent_adjustment_previous_value_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentadjustment",
            constraint=models.CheckConstraint(
                condition=models.Q(("new_value__gte", 0)),
                name="rent_adjustment_new_value_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("cpf_cnpj",),
                name="unique_active_tenant_cpf_cnpj",
            ),
        ),
    ]
