# Generated by Django 5.2.13 on 2026-06-08 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_condominium_building_condominium"),
        ("finances", "0003_reserve_condomonthclose_incomeentry_reservemovement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="billingaccount",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("water", "Água"),
                    ("electricity", "Luz"),
                    ("iptu", "IPTU"),
                    ("internet", "Internet"),
                    ("generic", "Genérica"),
                ],
                default="generic",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="billingaccount",
            name="holder_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="billingaccount",
            name="registered_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="billingaccount",
            name="secondary_identifier",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="billingaccount",
            name="supply_status",
            field=models.CharField(
                choices=[("active", "Ligada"), ("cut", "Cortada")],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="billingaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("building", "account_type", "external_identifier"),
                name="unique_active_billing_account_identity",
            ),
        ),
    ]
