# Generated by Django 5.2.13 on 2026-06-08 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0004_billingaccount_account_type_identity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="installmentplan",
            old_name="linked_billing_account",
            new_name="billing_account",
        ),
    ]
