# Generated by Django 5.2.13 on 2026-06-08 23:34

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

# Enable Row Level Security on the two new tables in the SAME migration that creates them
# (Supabase Data API exposure — .claude/rules/database.md + security.md + design §13). RLS
# with no policies denies the anon/authenticated Data API roles while the Django backend
# (postgres role, rolbypassrls=true, table owner) is unaffected. Static SQL (no f-strings)
# to avoid ruff S608. ENABLE on an already-enabled table is a no-op (idempotent).
ENABLE_RLS = """
ALTER TABLE public.finances_waterbillstatement ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.finances_electricitybillstatement ENABLE ROW LEVEL SECURITY;
"""

DISABLE_RLS = """
ALTER TABLE public.finances_waterbillstatement DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.finances_electricitybillstatement DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        (
            "finances",
            "0005_rename_linked_billing_account_installmentplan_billing_account",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectricityBillStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Data/hora de criação do registro",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Data/hora da última modificação",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        help_text="Indica se o registro foi excluído",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Data/hora da exclusão",
                        null=True,
                    ),
                ),
                ("consumo_kwh", models.PositiveIntegerField()),
                (
                    "energia_injetada_kwh",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "leitura_anterior",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("leitura_atual", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "leitura_dias",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("classe", models.CharField(blank=True, max_length=60)),
                ("bandeira", models.CharField(blank=True, max_length=40)),
                (
                    "bill",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="electricity_statement",
                        to="finances.bill",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Usuário que criou o registro",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Usuário que excluiu o registro",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Usuário que modificou o registro",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="WaterBillStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Data/hora de criação do registro",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Data/hora da última modificação",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        help_text="Indica se o registro foi excluído",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Data/hora da exclusão",
                        null=True,
                    ),
                ),
                ("consumo_m3", models.PositiveIntegerField()),
                (
                    "leitura_anterior",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("leitura_atual", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "leitura_dias",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("data_leitura", models.DateField(blank=True, null=True)),
                (
                    "agua_status",
                    models.CharField(
                        choices=[("active", "Ligada"), ("cut", "Cortada")],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "esgoto_status",
                    models.CharField(
                        choices=[("active", "Ligada"), ("cut", "Cortada")],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "bill",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="water_statement",
                        to="finances.bill",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Usuário que criou o registro",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Usuário que excluiu o registro",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Usuário que modificou o registro",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(sql=ENABLE_RLS, reverse_sql=DISABLE_RLS),
    ]
