# Generated by Django 5.2.13 on 2026-06-12 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0006_electricitybillstatement_waterbillstatement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bill",
            options={
                "default_manager_name": "objects",
                "ordering": ["-competence_month", "due_date"],
            },
        ),
        migrations.AlterModelOptions(
            name="billingaccount",
            options={"default_manager_name": "objects", "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="billlineitem",
            options={"default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "default_manager_name": "objects",
                "ordering": ["sort_order", "name"],
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="electricitybillstatement",
            options={"default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"default_manager_name": "objects", "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="incomeentry",
            options={"default_manager_name": "objects", "ordering": ["-income_date"]},
        ),
        migrations.AlterModelOptions(
            name="installment",
            options={
                "default_manager_name": "objects",
                "ordering": ["due_date", "number"],
            },
        ),
        migrations.AlterModelOptions(
            name="installmentplan",
            options={
                "default_manager_name": "objects",
                "ordering": ["start_due_date", "description"],
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"default_manager_name": "objects", "ordering": ["-payment_date"]},
        ),
        migrations.AlterModelOptions(
            name="paymentallocation",
            options={"default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="reserve",
            options={"default_manager_name": "objects", "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="reservemovement",
            options={
                "default_manager_name": "objects",
                "ordering": ["movement_date", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="waterbillstatement",
            options={"default_manager_name": "objects"},
        ),
        migrations.AlterModelManagers(
            name="bill",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="billingaccount",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="billlineitem",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="category",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="electricitybillstatement",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="employee",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="incomeentry",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="installment",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="installmentplan",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="payment",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="paymentallocation",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="reserve",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="reservemovement",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="waterbillstatement",
            managers=[],
        ),
    ]
