# Generated by Django 5.2.13 on 2026-06-12 03:41

import django.db.models.deletion
from django.db import migrations, models


def _backfill_materialized_and_payment_fk(apps, schema_editor):
    """Move PAID plans to MATERIALIZED and link existing reserve withdrawals to their Payment.

    Until this migration ``PAID`` was only ever set by ``_mark_completed_plans_paid`` (materialization
    without a real payment — there is no PAID-by-payment path yet), so EVERY existing PAID plan is in
    truth MATERIALIZED. Reserve withdrawals predating the new FK are matched to the reserve-funded
    Payment that allocated the same bill+amount; an ambiguous match (more than one candidate) is left
    null — the new path always sets the FK, and the old movements still reverse by absence (UI shows
    payment=null), so a wrong guess is worse than a null.
    """
    InstallmentPlan = apps.get_model("finances", "InstallmentPlan")
    InstallmentPlan.objects.filter(lifecycle_state="paid").update(lifecycle_state="materialized")

    ReserveMovement = apps.get_model("finances", "ReserveMovement")
    PaymentAllocation = apps.get_model("finances", "PaymentAllocation")
    withdrawals = ReserveMovement.objects.filter(
        kind="withdrawal", bill__isnull=False, payment__isnull=True
    )
    for movement in withdrawals:
        candidates = list(
            PaymentAllocation.objects.filter(
                bill_id=movement.bill_id,
                amount=movement.amount,
                payment__funded_from="reserve",
                payment__is_deleted=False,
            ).values_list("payment_id", flat=True)
        )
        if len(set(candidates)) == 1:
            movement.payment_id = candidates[0]
            movement.save(update_fields=["payment"])


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0007_alter_bill_options_alter_billingaccount_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservemovement",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reserve_movements",
                to="finances.payment",
            ),
        ),
        migrations.AlterField(
            model_name="installmentplan",
            name="lifecycle_state",
            field=models.CharField(
                choices=[
                    ("active", "Ativo"),
                    ("materialized", "Materializado"),
                    ("paid", "Quitado"),
                    ("deferred", "Adiado"),
                    ("canceled", "Cancelado"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            _backfill_materialized_and_payment_fk,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
