# Generated by Django 5.2.13 on 2026-07-13 02:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_core_data_integrity_constraints"),
        ("finances", "0008_installmentplan_materialized_reservemovement_payment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(fields=["lifecycle_state", "due_date"], name="bill_state_due_idx"),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["competence_month", "lifecycle_state"],
                name="bill_competence_state_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="installment",
            index=models.Index(fields=["due_date"], name="finance_inst_due_date_idx"),
        ),
    ]
