# Generated by Django 5.2.13 on 2026-07-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0009_b16_bill_installment_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="amount_is_estimated",
            field=models.BooleanField(default=False),
        ),
    ]
